
#pragma once
#define VIAL_KEYBOARD_UID {0xFE, 0x12, 0x76, 0xA2, 0x8D, 0xFA, 0xCF, 0x12}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 1}
#define VIAL_UNLOCK_COMBO_COLS { 0, 2 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 1
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define NO_ACTION_ONESHOT