
#pragma once
#define VIAL_KEYBOARD_UID {0x31, 0x89, 0x9B, 0xB5, 0x36, 0xFB, 0x1E, 0x1B}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 1}
#define VIAL_UNLOCK_COMBO_COLS { 0, 2 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define NO_ACTION_FUNCTION
#define NO_ACTION_ONESHOT